import { useState, useEffect, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Html5Qrcode } from 'html5-qrcode';
import { 
  QrCode, Camera, CheckCircle2, XCircle, AlertTriangle,
  User, Shield, Zap, Calendar, Clock, RefreshCw, CameraOff
} from 'lucide-react';

// ── Shared Hardware Concurrency Lock ─────────────────────────────────────────
// Ensures async start/stop operations are executed strictly in order.
// This completely avoids camera conflicts and resource locks on double renders.
let globalScannerInstance = null;
let globalScannerPromise = Promise.resolve();

// ── Utility ────────────────────────────────────────────────────────────────
const parseQRToken = (raw) => {
  try {
    const data = JSON.parse(raw);
    // Validate required fields
    if (!data.memberId && !data.id) throw new Error('Invalid token: no member ID');
    
    const now = Date.now();
    const expires = data.expires || 0;
    const isExpired = expires > 0 && now > expires;
    const secondsLeft = expires > 0 ? Math.max(0, Math.round((expires - now) / 1000)) : null;

    return {
      valid: !isExpired,
      isExpired,
      secondsLeft,
      memberId: data.memberId || data.id,
      name: data.name,
      plan: data.plan,
      gym: data.gym,
      issued: data.issued ? new Date(data.issued) : null,
      nonce: data.nonce || null,
    };
  } catch {
    return { valid: false, parseError: true, raw };
  }
};

const formatTime = (date) => {
  if (!date) return '—';
  return date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit' });
};

// ── Scan Result Card ─────────────────────────────────────────────────────────
const ScanResult = ({ result, onReset }) => {
  if (result.parseError) {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="glassmorphism rounded-3xl p-8 border border-red-500/30 text-center space-y-4"
      >
        <div className="w-20 h-20 rounded-full bg-red-500/10 border border-red-500/20 flex items-center justify-center mx-auto">
          <XCircle size={40} className="text-red-500" />
        </div>
        <div>
          <h3 className="text-white font-black text-xl uppercase mb-1">Invalid QR Code</h3>
          <p className="text-gray-500 text-sm">This QR code was not generated by The Personality Gym.</p>
        </div>
        <div className="bg-black/30 rounded-xl p-3 text-left break-all">
          <p className="text-gray-600 text-[10px] font-mono">{result.raw}</p>
        </div>
        <button
          onClick={onReset}
          className="w-full py-3 bg-white/5 hover:bg-white/10 text-white font-black uppercase tracking-widest text-xs rounded-xl transition-all flex items-center justify-center gap-2"
        >
          <RefreshCw size={14} /> Scan Again
        </button>
      </motion.div>
    );
  }

  if (result.isExpired) {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="glassmorphism rounded-3xl p-8 border border-yellow-500/30 text-center space-y-4"
      >
        <div className="w-20 h-20 rounded-full bg-yellow-500/10 border border-yellow-500/20 flex items-center justify-center mx-auto">
          <AlertTriangle size={40} className="text-yellow-500" />
        </div>
        <div>
          <h3 className="text-white font-black text-xl uppercase mb-1">QR Code Expired</h3>
          <p className="text-gray-500 text-sm">
            Token for <span className="text-white font-bold">{result.name}</span> has expired.
            Ask the member to regenerate their gate pass.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-white/5 rounded-xl p-3 text-center">
            <p className="text-gray-500 text-[9px] uppercase font-bold tracking-widest mb-1">Member</p>
            <p className="text-white font-bold text-sm">{result.name}</p>
          </div>
          <div className="bg-white/5 rounded-xl p-3 text-center">
            <p className="text-gray-500 text-[9px] uppercase font-bold tracking-widest mb-1">Member ID</p>
            <p className="text-white font-mono font-bold text-sm">{result.memberId}</p>
          </div>
        </div>
        <button
          onClick={onReset}
          className="w-full py-3 bg-yellow-500/10 hover:bg-yellow-500/20 text-yellow-400 font-black uppercase tracking-widest text-xs rounded-xl border border-yellow-500/20 transition-all flex items-center justify-center gap-2"
        >
          <RefreshCw size={14} /> Scan Again
        </button>
      </motion.div>
    );
  }

  // ✅ Valid member
  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      className="space-y-4"
    >
      {/* Success Header */}
      <div className="glassmorphism rounded-3xl p-6 border border-green-500/30 text-center space-y-3 relative overflow-hidden">
        <div className="absolute inset-0 bg-green-500/5 pointer-events-none" />
        <motion.div
          animate={{ scale: [1, 1.1, 1] }}
          transition={{ duration: 0.5 }}
          className="w-20 h-20 rounded-full bg-green-500/10 border-2 border-green-500/40 flex items-center justify-center mx-auto"
        >
          <CheckCircle2 size={40} className="text-green-400" />
        </motion.div>
        <div className="relative z-10">
          <p className="text-green-400 text-xs font-black uppercase tracking-[0.3em] mb-1">Access Granted</p>
          <h3 className="text-white font-black text-2xl uppercase">{result.name}</h3>
          <p className="text-gray-400 text-sm font-bold mt-1">{result.gym}</p>
        </div>
      </div>

      {/* Member Details Grid */}
      <div className="grid grid-cols-2 gap-3">
        <div className="glassmorphism rounded-2xl p-4 border border-white/5 space-y-1">
          <p className="text-gray-500 text-[9px] uppercase font-black tracking-widest flex items-center gap-1">
            <Shield size={9} className="text-gym-orange" /> Member ID
          </p>
          <p className="text-white font-mono font-bold text-sm">{result.memberId}</p>
        </div>
        <div className="glassmorphism rounded-2xl p-4 border border-white/5 space-y-1">
          <p className="text-gray-500 text-[9px] uppercase font-black tracking-widest flex items-center gap-1">
            <Zap size={9} className="text-gym-orange" /> Plan
          </p>
          <p className="text-white font-bold text-sm">{result.plan}</p>
        </div>
        <div className="glassmorphism rounded-2xl p-4 border border-white/5 space-y-1">
          <p className="text-gray-500 text-[9px] uppercase font-black tracking-widest flex items-center gap-1">
            <Clock size={9} className="text-green-400" /> Issued At
          </p>
          <p className="text-white font-bold text-sm">{formatTime(result.issued)}</p>
        </div>
        <div className="glassmorphism rounded-2xl p-4 border border-white/5 space-y-1">
          <p className="text-gray-500 text-[9px] uppercase font-black tracking-widest flex items-center gap-1">
            <CheckCircle2 size={9} className="text-green-400" /> Token Valid
          </p>
          <p className="text-green-400 font-bold text-sm">
            {result.secondsLeft !== null ? `${result.secondsLeft}s left` : 'Valid'}
          </p>
        </div>
      </div>

      {/* Nonce (proof of one-time use) */}
      {result.nonce && (
        <div className="glassmorphism rounded-2xl p-4 border border-white/5 flex items-center justify-between">
          <div>
            <p className="text-gray-500 text-[9px] uppercase font-black tracking-widest mb-1">Session Nonce (One-Time Token)</p>
            <p className="text-gym-orange font-mono font-bold text-sm tracking-wider">{result.nonce}</p>
          </div>
          <div className="w-8 h-8 rounded-lg bg-green-500/10 border border-green-500/20 flex items-center justify-center">
            <CheckCircle2 size={16} className="text-green-400" />
          </div>
        </div>
      )}

      {/* Mark Check-In Button */}
      <button className="w-full py-4 bg-green-500 hover:bg-green-400 text-white font-black uppercase tracking-widest text-sm rounded-2xl transition-all shadow-[0_0_20px_rgba(34,197,94,0.3)] active:scale-95 flex items-center justify-center gap-3">
        <CheckCircle2 size={20} />
        Mark Check-In for {result.name}
      </button>

      <button
        onClick={onReset}
        className="w-full py-3 bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white font-black uppercase tracking-widest text-xs rounded-2xl transition-all flex items-center justify-center gap-2"
      >
        <RefreshCw size={14} /> Scan Another Member
      </button>
    </motion.div>
  );
};

// ── QR Scanner Component ─────────────────────────────────────────────────────
const QRScannerView = ({ onScan }) => {
  const scannerRef = useRef(null);
  const html5QrRef = useRef(null);
  const [error, setError] = useState(null);
  const [isStarting, setIsStarting] = useState(true);

  useEffect(() => {
    let isMounted = true;
    const scannerId = 'qr-reader-admin';

    // Direct browser hardware shutoff: finds all videos and terminates active stream tracks
    // This turns off the webcam hardware light instantly, independent of library states.
    const stopHardwareCamera = () => {
      try {
        const videos = document.querySelectorAll('video');
        videos.forEach(video => {
          if (video.srcObject && video.srcObject instanceof MediaStream) {
            const stream = video.srcObject;
            stream.getTracks().forEach(track => {
              try { track.stop(); } catch (e) {}
            });
            video.srcObject = null;
          }
        });
      } catch (e) {
        console.warn("Failed directly stopping hardware camera:", e);
      }
    };

    const init = async () => {
      // 1. Await any existing scanner shut-down operations to finish first
      await globalScannerPromise;

      if (!isMounted) return;

      try {
        const container = document.getElementById(scannerId);
        if (container) container.innerHTML = '';

        const scanner = new Html5Qrcode(scannerId);
        globalScannerInstance = scanner;
        html5QrRef.current = scanner;

        // 2. Start the scan and assign the promise to the shared chain
        globalScannerPromise = scanner.start(
          { facingMode: 'environment' },
          { fps: 10, qrbox: { width: 240, height: 240 } },
          (decodedText) => {
            if (isMounted) onScan(decodedText);
          },
          () => {} // ignore local frame decode errors
        );

        await globalScannerPromise;

        if (!isMounted) {
          if (scanner.isScanning) {
            await scanner.stop();
          }
          stopHardwareCamera();
        } else {
          setIsStarting(false);
        }
      } catch (err) {
        if (isMounted) {
          setError(`Camera error: ${err}`);
          setIsStarting(false);
        }
      }
    };

    init();

    return () => {
      isMounted = false;

      if (globalScannerInstance) {
        const scannerToStop = globalScannerInstance;
        globalScannerInstance = null;

        // Chain the shutdown operation into the shared lock sequence
        globalScannerPromise = (async () => {
          try {
            // Wait for start to fully resolve so we can safely stop it
            await globalScannerPromise;
            if (scannerToStop.isScanning) {
              await scannerToStop.stop();
            }
          } catch (e) {}
          stopHardwareCamera();
          const container = document.getElementById(scannerId);
          if (container) container.innerHTML = '';
        })();
      } else {
        stopHardwareCamera();
        const container = document.getElementById(scannerId);
        if (container) container.innerHTML = '';
      }
    };
  }, [onScan]);

  return (
    <div className="space-y-4">
      {error ? (
        <div className="glassmorphism rounded-3xl p-8 border border-red-500/20 text-center space-y-4">
          <CameraOff size={40} className="text-red-400 mx-auto" />
          <div>
            <p className="text-white font-black text-lg uppercase mb-2">Camera Access Denied</p>
            <p className="text-gray-500 text-sm">{error}</p>
            <p className="text-gray-600 text-xs mt-2">Please allow camera access in your browser settings and reload the page.</p>
          </div>
        </div>
      ) : (
        <>
          <div className="relative overflow-hidden rounded-3xl bg-black border border-white/10 shadow-2xl">
            {isStarting && (
              <div className="absolute inset-0 flex items-center justify-center bg-black/80 z-10 rounded-3xl">
                <div className="text-center space-y-3">
                  <div className="w-10 h-10 border-2 border-gym-orange/30 border-t-gym-orange rounded-full animate-spin mx-auto" />
                  <p className="text-gray-400 text-xs font-bold uppercase tracking-widest">Starting Camera…</p>
                </div>
              </div>
            )}
            {/* Scanning overlay crosshair */}
            <div className="absolute inset-0 z-10 flex items-center justify-center pointer-events-none">
              <div className="w-52 h-52 relative">
                {/* Corner brackets */}
                <div className="absolute top-0 left-0 w-8 h-8 border-t-2 border-l-2 border-gym-orange rounded-tl-lg" />
                <div className="absolute top-0 right-0 w-8 h-8 border-t-2 border-r-2 border-gym-orange rounded-tr-lg" />
                <div className="absolute bottom-0 left-0 w-8 h-8 border-b-2 border-l-2 border-gym-orange rounded-bl-lg" />
                <div className="absolute bottom-0 right-0 w-8 h-8 border-b-2 border-r-2 border-gym-orange rounded-br-lg" />
                {/* Scan line */}
                <motion.div
                  animate={{ top: ['10%', '90%', '10%'] }}
                  transition={{ duration: 2.5, repeat: Infinity, ease: 'linear' }}
                  className="absolute left-2 right-2 h-0.5 bg-gradient-to-r from-transparent via-gym-orange to-transparent"
                  style={{ position: 'absolute' }}
                />
              </div>
            </div>
            <div id="qr-reader-admin" className="w-full" />
          </div>
          <p className="text-gray-500 text-xs font-bold uppercase tracking-widest text-center">
            Point camera at the member's Gate Pass QR
          </p>
        </>
      )}
    </div>
  );
};

// ── Main Page ────────────────────────────────────────────────────────────────
const CheckIn = () => {
  const [phase, setPhase] = useState('idle'); // idle | scanning | result
  const [scanResult, setScanResult] = useState(null);

  const handleScan = useCallback((raw) => {
    const parsed = parseQRToken(raw);
    setScanResult(parsed);
    setPhase('result');
  }, []);

  const handleReset = () => {
    setScanResult(null);
    setPhase('idle');
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-2xl mx-auto space-y-8 pb-12"
    >
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-black text-white uppercase italic">Check-In Scanner</h2>
          <p className="text-gray-500 text-sm font-bold mt-1">
            Scan member's Gate Pass QR to verify and grant entry
          </p>
        </div>
        <div className="w-14 h-14 rounded-2xl bg-gym-orange/10 border border-gym-orange/20 flex items-center justify-center">
          <QrCode size={28} className="text-gym-orange" />
        </div>
      </div>

      {/* How it works strip */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { icon: <QrCode size={18} />, step: '1', label: 'Member opens app & taps card' },
          { icon: <Camera size={18} />, step: '2', label: 'Admin scans the Gate Pass QR' },
          { icon: <CheckCircle2 size={18} />, step: '3', label: 'Member data verified instantly' },
        ].map((s) => (
          <div key={s.step} className="glassmorphism rounded-2xl p-4 border border-white/5 text-center space-y-2">
            <div className="w-8 h-8 rounded-lg bg-gym-orange/10 text-gym-orange flex items-center justify-center mx-auto">
              {s.icon}
            </div>
            <p className="text-gray-400 text-[10px] font-bold uppercase tracking-wide leading-tight">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Main Action Area */}
      <AnimatePresence mode="wait">
        {phase === 'idle' && (
          <motion.div
            key="idle"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="glassmorphism rounded-3xl p-10 border border-white/5 text-center space-y-6"
          >
            <div className="w-24 h-24 rounded-full bg-gym-orange/10 border-2 border-gym-orange/20 flex items-center justify-center mx-auto">
              <QrCode size={44} className="text-gym-orange" />
            </div>
            <div>
              <h3 className="text-white font-black text-2xl uppercase mb-2">Ready to Scan</h3>
              <p className="text-gray-500 text-sm">
                Click below to activate your camera and scan a member's Gate Pass QR code.
              </p>
            </div>
            <button
              onClick={() => setPhase('scanning')}
              className="inline-flex items-center gap-3 px-8 py-4 bg-gym-orange text-white font-black uppercase tracking-widest text-sm rounded-2xl hover:bg-gym-neon transition-all shadow-[0_0_25px_rgba(255,87,34,0.3)] active:scale-95"
            >
              <Camera size={20} />
              Start Camera Scanner
            </button>
          </motion.div>
        )}

        {phase === 'scanning' && (
          <motion.div
            key="scanning"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="space-y-4"
          >
            <div className="flex justify-between items-center">
              <p className="text-white font-black text-base uppercase">Live Camera</p>
              <button
                onClick={handleReset}
                className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white text-xs font-bold uppercase tracking-widest rounded-xl transition-all"
              >
                <CameraOff size={14} /> Stop
              </button>
            </div>
            <QRScannerView onScan={handleScan} />
          </motion.div>
        )}

        {phase === 'result' && scanResult && (
          <motion.div
            key="result"
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
          >
            <ScanResult result={scanResult} onReset={handleReset} />
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default CheckIn;
